language: node_js
node_js:
  - "12"

branches:
  only:
    - master

install:
  - npm install

before_script:
  - git config --global user.name 'cokia'
  - git config --global user.email 'hwymaster01@gmail.com'
  - sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
  - hexo clean
  - hexo generate
  - hexo deploy
